// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0G47RtYafjsciPFSNLgTNlAtgw_LkdGg',
    appId: '1:875496895423:web:934db15bb2a6099caf270a',
    messagingSenderId: '875496895423',
    projectId: 'pokemon-app-1309c',
    authDomain: 'pokemon-app-1309c.firebaseapp.com',
    storageBucket: 'pokemon-app-1309c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjr9EJUlHC_uVIUiN2M9AAVJK-Tdyh8BM',
    appId: '1:875496895423:android:dd6861cee712a192af270a',
    messagingSenderId: '875496895423',
    projectId: 'pokemon-app-1309c',
    storageBucket: 'pokemon-app-1309c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQDmuCNLCM82PKJ4gzc3ZQtzE7Uzd-2F4',
    appId: '1:875496895423:ios:1c7d2ef27040d207af270a',
    messagingSenderId: '875496895423',
    projectId: 'pokemon-app-1309c',
    storageBucket: 'pokemon-app-1309c.firebasestorage.app',
    iosBundleId: 'com.example.imMottuMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQDmuCNLCM82PKJ4gzc3ZQtzE7Uzd-2F4',
    appId: '1:875496895423:ios:1c7d2ef27040d207af270a',
    messagingSenderId: '875496895423',
    projectId: 'pokemon-app-1309c',
    storageBucket: 'pokemon-app-1309c.firebasestorage.app',
    iosBundleId: 'com.example.imMottuMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0G47RtYafjsciPFSNLgTNlAtgw_LkdGg',
    appId: '1:875496895423:web:82f14caabfe10fcdaf270a',
    messagingSenderId: '875496895423',
    projectId: 'pokemon-app-1309c',
    authDomain: 'pokemon-app-1309c.firebaseapp.com',
    storageBucket: 'pokemon-app-1309c.firebasestorage.app',
  );
}
